import 'dotenv/config';
import Fastify from 'fastify';
import type { FastifyRequest } from 'fastify';
import cors from '@fastify/cors';
import { createClient } from '@supabase/supabase-js';
import { ChatHandler } from './chat-handler.js';
import { GenerationHandler } from './generation-handler.js';
import fastifyRateLimit from '@fastify/rate-limit';
import { resolveVpsSharedSecret, routeRequirementForPath, verifyVpsTicket } from './auth.js';
import { logger } from './utils.js';

const PORT = process.env.PORT ? parseInt(process.env.PORT, 10) : 3001;
const HOST = process.env.HOST || '0.0.0.0';

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY;
const QDRANT_URL = process.env.QDRANT_URL || 'http://localhost:6333';
const QDRANT_API_KEY = process.env.QDRANT_API_KEY;
const VPS_SHARED_SECRET = resolveVpsSharedSecret();

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  logger.error('Missing SUPABASE_URL or SUPABASE_ANON_KEY');
  process.exit(1);
}
if (!VPS_SHARED_SECRET.ok) {
  logger.error('AI gateway authentication is not configured', { code: VPS_SHARED_SECRET.code });
  process.exit(1);
}
const VPS_SHARED_SECRET_VALUE = VPS_SHARED_SECRET.secret;

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: { persistSession: false, autoRefreshToken: false }
});

const chatHandler = new ChatHandler(supabase);
const generationHandler = new GenerationHandler(supabase, QDRANT_URL, QDRANT_API_KEY);

async function buildServer() {
  const server = Fastify({
    logger: true,
    bodyLimit: 50 * 1024 * 1024,
  });

  await server.register(cors, {
    origin: true,
    credentials: true,
    allowedHeaders: ['Content-Type', 'Authorization', 'apikey', 'x-correlation-id'],
  });

  await server.register(fastifyRateLimit, {
    max: (req: FastifyRequest) => {
      const plan = (req.headers['x-user-plan'] as string) || 'free';
      return plan === 'free' ? 5 : 20; // 5 req/min for free, 20 for pro
    },
    timeWindow: '1 minute',
    keyGenerator: (req: FastifyRequest) => (req.headers['x-user-id'] as string) || req.ip,
  });

  server.addHook('preHandler', async (request, reply) => {
    const path = request.url;
    if (path === '/health') return;

    const authHeader = request.headers.authorization;
    const apiKey = request.headers.apikey;

    if (!authHeader && !apiKey) {
      reply.code(401).send({ error: 'missing_auth', message: 'Authorization required' });
      return;
    }

    const expectedRoute = routeRequirementForPath(path);
    if (!expectedRoute) {
      reply.code(404).send({ error: 'unknown_route', message: 'Gateway route is not available' });
      return;
    }

    const token = authHeader?.replace(/^Bearer\s+/i, '') || String(apiKey || '');

    // We expect a VPS ticket generated by Next.js
    const ticketData = await verifyVpsTicket(token, VPS_SHARED_SECRET_VALUE, expectedRoute);

    if (!ticketData) {
      reply.code(401).send({ error: 'invalid_token', message: 'Invalid or expired ticket' });
      return;
    }

    request.headers['x-user-id'] = ticketData.userId;
    request.headers['x-user-plan'] = ticketData.plan;
    request.headers['x-user-feature'] = ticketData.feature;
    request.headers['x-user-feature-key'] = ticketData.featureKey;
    if (ticketData.ticketId) {
      request.headers['x-ticket-id'] = ticketData.ticketId;
    }
  });

  server.post('/chat/au-chat', async (request, reply) => {
    return chatHandler.handleAuChat(request.body as any, request.headers as any, reply);
  });

  server.post('/chat/global-chat', async (request, reply) => {
    return chatHandler.handleGlobalChat(request.body as any, request.headers as any, reply);
  });

  server.post('/chat/legacy', async (request, reply) => {
    return chatHandler.handleLegacyChat(request.body as any, request.headers as any, reply);
  });

  server.post('/generate/knowledge', async (request, reply) => {
    return generationHandler.handleKnowledge(request.body as any, request.headers as any, reply);
  });

  server.post('/generate/exam-predictions', async (request, reply) => {
    return generationHandler.handleExamPredictions(request.body as any, request.headers as any, reply);
  });

  server.post('/generate/practice-exam', async (request, reply) => {
    return generationHandler.handlePracticeExam(request.body as any, request.headers as any, reply);
  });

  server.post('/generate/prompt-starters', async (request, reply) => {
    return generationHandler.handlePromptStarters(request.body as any, request.headers as any, reply);
  });

  server.get('/health', async () => {
    return { status: 'ok', timestamp: new Date().toISOString() };
  });

  return server;
}

async function main() {
  const server = await buildServer();
  
  await server.listen({ port: PORT, host: HOST });
  logger.info(`VPS AI Gateway listening on ${HOST}:${PORT}`);
  logger.info(`Supabase URL: ${SUPABASE_URL}`);
  logger.info(`Qdrant URL: ${QDRANT_URL}`);
  logger.info(`OpenRouter key: ${process.env.OPENROUTER_API_KEY ? '***set***' : 'NOT SET'}`);
  logger.info(`Node ${process.version}, PID ${process.pid}`);

  // ── Graceful shutdown ──────────────────────────────────────────────────
  // PM2 sends SIGINT; Docker/systemd send SIGTERM.
  // Give in-flight requests up to 10s to drain before force-exiting.
  const shutdown = async (signal: string) => {
    logger.info(`Received ${signal} — shutting down gracefully…`);
    const forceTimer = setTimeout(() => {
      logger.error('Graceful shutdown timed out after 10s — forcing exit');
      process.exit(1);
    }, 10_000);
    try {
      await server.close();
      clearTimeout(forceTimer);
      logger.info('Server closed cleanly');
      process.exit(0);
    } catch (err) {
      clearTimeout(forceTimer);
      logger.error('Error during shutdown', err);
      process.exit(1);
    }
  };

  process.on('SIGTERM', () => shutdown('SIGTERM'));
  process.on('SIGINT', () => shutdown('SIGINT'));

  // Catch unhandled rejections in production
  process.on('unhandledRejection', (reason) => {
    logger.error('Unhandled rejection', reason);
  });
  process.on('uncaughtException', (err) => {
    logger.error('Uncaught exception — exiting', err);
    process.exit(1);
  });
}

main().catch(err => {
  logger.error('Failed to start server', err);
  process.exit(1);
});
