import 'dotenv/config';
import Fastify from 'fastify';
import type { FastifyRequest } from 'fastify';
import cors from '@fastify/cors';
import { createClient } from '@supabase/supabase-js';
import { ChatHandler } from './chat-handler.js';
import { GenerationHandler } from './generation-handler.js';
import fastifyRateLimit from '@fastify/rate-limit';
import {
  isOriginAllowed,
  resolveAllowedOrigins,
  resolveVpsSharedSecret,
  routeRequirementForPath,
  verifyVpsTicket,
} from './auth.js';
import { errorLogDetails, logger, parsePositiveInt } from './utils.js';

const PORT = parsePositiveInt(process.env.PORT, 3001);
const HOST = process.env.HOST || '0.0.0.0';
const IS_PRODUCTION = process.env.NODE_ENV === 'production';

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVER_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const QDRANT_URL = process.env.QDRANT_URL || 'http://localhost:6333';
const QDRANT_API_KEY = process.env.QDRANT_API_KEY;
const VPS_SHARED_SECRET = resolveVpsSharedSecret();
const ALLOWED_ORIGINS = resolveAllowedOrigins();
const RATE_LIMIT_MAX = parsePositiveInt(process.env.RATE_LIMIT_MAX_PER_MINUTE, 20);

if (!SUPABASE_URL || !SUPABASE_SERVER_KEY) {
  logger.error('Missing Supabase service-role server configuration');
  process.exit(1);
}
if (!VPS_SHARED_SECRET.ok) {
  logger.error('AI gateway authentication is not configured', { code: VPS_SHARED_SECRET.code });
  process.exit(1);
}
if (!ALLOWED_ORIGINS.ok) {
  logger.error('AI gateway CORS is not configured', { code: ALLOWED_ORIGINS.code });
  process.exit(1);
}
const VPS_SHARED_SECRET_VALUE = VPS_SHARED_SECRET.secret;
const supabase = createClient(SUPABASE_URL, SUPABASE_SERVER_KEY, {
  auth: { persistSession: false, autoRefreshToken: false }
});
const allowedOrigins = ALLOWED_ORIGINS.origins;

function isInsecurePublicQdrantUrl(rawUrl: string): boolean {
  try {
    const parsed = new URL(rawUrl);
    const hostname = parsed.hostname.toLowerCase();
    const isLoopback = hostname === 'localhost' || hostname === '127.0.0.1' || hostname === '::1';
    return IS_PRODUCTION && parsed.protocol !== 'https:' && !isLoopback;
  } catch {
    return true;
  }
}

const chatHandler = new ChatHandler(supabase, QDRANT_URL, QDRANT_API_KEY);
const generationHandler = new GenerationHandler(supabase, QDRANT_URL, QDRANT_API_KEY);

async function buildServer() {
  const server = Fastify({
    logger: {
      redact: [
        'req.headers.authorization',
        'req.headers.apikey',
        'req.headers.cookie',
        'req.headers["x-api-key"]',
        'request.headers.authorization',
        'request.headers.apikey',
        'request.headers.cookie',
      ],
    },
    bodyLimit: 50 * 1024 * 1024,
  });

  await server.register(cors, {
    origin: (origin, callback) => {
      callback(null, isOriginAllowed(origin, allowedOrigins));
    },
    credentials: true,
    allowedHeaders: ['Content-Type', 'Authorization', 'Accept', 'x-correlation-id'],
  });

  await server.register(fastifyRateLimit, {
    max: RATE_LIMIT_MAX,
    timeWindow: '1 minute',
    keyGenerator: (req: FastifyRequest) => req.ip,
  });

  server.setNotFoundHandler(async (_request, reply) => {
    return reply.code(404).send({ error: 'unknown_route', message: 'Gateway route is not available' });
  });

  server.setErrorHandler(async (err, request, reply) => {
    logger.error('Unhandled gateway request error', {
      path: request.url.split('?')[0],
      error: errorLogDetails(err),
    });
    const statusCode = Number((err as any).statusCode || 500);
    const safeStatus = statusCode >= 400 && statusCode < 500 ? statusCode : 500;
    return reply.code(safeStatus).send({
      error: safeStatus === 500 ? 'gateway_error' : 'request_failed',
      message: safeStatus === 500 ? 'Gateway request failed' : 'Request failed',
    });
  });

  server.addHook('preHandler', async (request, reply) => {
    const path = request.url.split('?')[0] || '/';
    if (path === '/health') return;

    const authHeader = request.headers.authorization;

    if (!authHeader) {
      reply.code(401).send({ error: 'missing_auth', message: 'Authorization required' });
      return;
    }

    const expectedRoute = routeRequirementForPath(path);
    if (!expectedRoute) {
      reply.code(404).send({ error: 'unknown_route', message: 'Gateway route is not available' });
      return;
    }

    const token = authHeader.replace(/^Bearer\s+/i, '');

    // We expect a VPS ticket generated by Next.js
    const ticketData = await verifyVpsTicket(token, VPS_SHARED_SECRET_VALUE, expectedRoute);

    if (!ticketData) {
      reply.code(401).send({ error: 'invalid_token', message: 'Invalid or expired ticket' });
      return;
    }

    request.headers['x-user-id'] = ticketData.userId;
    request.headers['x-user-plan'] = ticketData.plan;
    request.headers['x-user-feature'] = ticketData.feature;
    request.headers['x-user-feature-key'] = ticketData.featureKey;
    request.headers['x-user-route'] = ticketData.route;
    request.headers['x-usage-reservation-id'] = ticketData.reservationId;
    request.headers['x-usage-idempotency-key'] = ticketData.idempotencyKey;
    if (ticketData.ticketId) {
      request.headers['x-ticket-id'] = ticketData.ticketId;
    }
  });

  server.post('/chat/au-chat', async (request, reply) => {
    return chatHandler.handleAuChat(request.body as any, request.headers as any, reply);
  });

  server.post('/chat/global-chat', async (request, reply) => {
    return chatHandler.handleGlobalChat(request.body as any, request.headers as any, reply);
  });

  server.post('/chat/legacy', async (request, reply) => {
    return chatHandler.handleLegacyChat(request.body as any, request.headers as any, reply);
  });

  server.post('/generate/knowledge', async (request, reply) => {
    return generationHandler.handleKnowledge(request.body as any, request.headers as any, reply);
  });

  server.post('/generate/exam-predictions', async (request, reply) => {
    return generationHandler.handleExamPredictions(request.body as any, request.headers as any, reply);
  });

  server.post('/generate/practice-exam', async (request, reply) => {
    return generationHandler.handlePracticeExam(request.body as any, request.headers as any, reply);
  });

  server.post('/generate/prompt-starters', async (request, reply) => {
    return generationHandler.handlePromptStarters(request.body as any, request.headers as any, reply);
  });

  server.get('/health', async () => {
    return { status: 'ok', timestamp: new Date().toISOString() };
  });

  return server;
}

async function main() {
  const server = await buildServer();
  
  await server.listen({ port: PORT, host: HOST });
  logger.info(`VPS AI Gateway listening on ${HOST}:${PORT}`);
  logger.info('Gateway dependency status', {
    supabaseConfigured: Boolean(SUPABASE_URL),
    qdrantConfigured: Boolean(QDRANT_URL),
    qdrantHttpsOrLoopback: !isInsecurePublicQdrantUrl(QDRANT_URL),
    allowedOriginCount: allowedOrigins.size,
    openRouterConfigured: Boolean(process.env.OPENROUTER_API_KEY || process.env.OPENAI_API_KEY),
    anthropicConfigured: Boolean(process.env.ANTHROPIC_API_KEY),
  });
  logger.info(`Node ${process.version}, PID ${process.pid}`);

  // ── Graceful shutdown ──────────────────────────────────────────────────
  // PM2 sends SIGINT; Docker/systemd send SIGTERM.
  // Give in-flight requests up to 10s to drain before force-exiting.
  const shutdown = async (signal: string) => {
    logger.info(`Received ${signal} — shutting down gracefully…`);
    const forceTimer = setTimeout(() => {
      logger.error('Graceful shutdown timed out after 10s — forcing exit');
      process.exit(1);
    }, 10_000);
    try {
      await server.close();
      clearTimeout(forceTimer);
      logger.info('Server closed cleanly');
      process.exit(0);
    } catch (err) {
      clearTimeout(forceTimer);
      logger.error('Error during shutdown', errorLogDetails(err));
      process.exit(1);
    }
  };

  process.on('SIGTERM', () => shutdown('SIGTERM'));
  process.on('SIGINT', () => shutdown('SIGINT'));

  // Catch unhandled rejections in production
  process.on('unhandledRejection', (reason) => {
    logger.error('Unhandled rejection', errorLogDetails(reason));
  });
  process.on('uncaughtException', (err) => {
    logger.error('Uncaught exception — exiting', errorLogDetails(err));
    process.exit(1);
  });
}

main().catch(err => {
  logger.error('Failed to start server', errorLogDetails(err));
  process.exit(1);
});
