"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TIER_TUNING_POLICY = exports.TIER_QUOTA_POLICIES = exports.TIER_FEATURE_POLICIES = exports.FIXED_MAX_DOCUMENTS_UPLOADED_TOTAL = exports.FLAGGED_MAX_UPLOAD_MB = exports.DEFAULT_MAX_UPLOAD_MB = exports.UPLOAD_SIZE_FEATURE_FLAG = exports.PROMO_PRO_END_UTC_ISO = exports.PROMO_PRO_END_LAGOS_ISO = void 0;
exports.toTierRuntime = toTierRuntime;
exports.isProLikeTier = isProLikeTier;
exports.tierDisplayLabel = tierDisplayLabel;
exports.getFeaturePolicy = getFeaturePolicy;
exports.getQuotaPolicy = getQuotaPolicy;
exports.isFeatureAllowedForTier = isFeatureAllowedForTier;
exports.limitUpgradeHref = limitUpgradeHref;
exports.featureUpgradeHref = featureUpgradeHref;
exports.getUpgradeBenefits = getUpgradeBenefits;
exports.isPromoWindowActive = isPromoWindowActive;
exports.PROMO_PRO_END_LAGOS_ISO = '2026-04-02T00:00:00+01:00';
exports.PROMO_PRO_END_UTC_ISO = '2026-04-01T23:00:00.000Z';
exports.UPLOAD_SIZE_FEATURE_FLAG = 'upload_100mb';
exports.DEFAULT_MAX_UPLOAD_MB = 50;
exports.FLAGGED_MAX_UPLOAD_MB = 100;
exports.FIXED_MAX_DOCUMENTS_UPLOADED_TOTAL = {
    free: 4,
    pro: 10,
};
exports.TIER_FEATURE_POLICIES = [
    {
        key: 'au_chat',
        title: 'AU Chat (single document)',
        description: 'Core chat against selected document context.',
        allowedTiers: ['FREE', 'PRO', 'PROMO_PRO'],
        uiEntryPoints: ['/dashboard/chat'],
        serverEnforcement: ['/api/proxy/chat', '/api/proxy/au-chat'],
        quotaKey: 'messages_per_day',
    },
    {
        key: 'global_chat',
        title: 'Global Chat (cross-library)',
        description: 'Cross-document assistant using broader memory and context.',
        allowedTiers: ['PRO', 'PROMO_PRO'],
        uiEntryPoints: ['/dashboard/global-chat'],
        serverEnforcement: ['/api/proxy/global-chat'],
    },
    {
        key: 'knowledge_generation',
        title: 'Knowledge Generation',
        description: 'Summary, key points, concept mapping, roadmap generation.',
        allowedTiers: ['FREE', 'PRO', 'PROMO_PRO'],
        uiEntryPoints: ['/dashboard/knowledge'],
        serverEnforcement: ['/api/proxy/generate-knowledge'],
        quotaKey: 'knowledge_generations_per_day',
    },
    {
        key: 'practice_exam_generation',
        title: 'Practice Exam Generation',
        description: 'Generates exam simulations from textbook and past questions.',
        allowedTiers: ['PRO', 'PROMO_PRO'],
        uiEntryPoints: ['/dashboard/practice'],
        serverEnforcement: ['/api/proxy/exam-generator'],
        quotaKey: 'practice_exams_per_day',
    },
    {
        key: 'exam_predictions',
        title: 'Exam Prediction Engine',
        description: 'Pattern-weighted exam prediction generation.',
        allowedTiers: ['PRO', 'PROMO_PRO'],
        uiEntryPoints: ['/dashboard/predictions'],
        serverEnforcement: ['/api/proxy/prediction-engine'],
        quotaKey: 'predictions_per_day',
    },
    {
        key: 'premium_models',
        title: 'Premium Model Access',
        description: 'Paid model families and highest quality routing.',
        allowedTiers: ['PRO', 'PROMO_PRO'],
        uiEntryPoints: ['/dashboard/chat', '/dashboard/global-chat'],
        serverEnforcement: ['/api/proxy/[functionName] model selection'],
    },
    {
        key: 'advanced_memory',
        title: 'Advanced Memory Depth',
        description: 'Higher turn window and larger retrieval depth.',
        allowedTiers: ['PRO', 'PROMO_PRO'],
        uiEntryPoints: ['/dashboard/chat', '/dashboard/global-chat'],
        serverEnforcement: ['/api/proxy/chat payload clamp'],
    },
    {
        key: 'priority_worker_queue',
        title: 'Priority Worker Throughput',
        description: 'Higher concurrent processing throughput for ingestion jobs.',
        allowedTiers: ['PRO', 'PROMO_PRO'],
        uiEntryPoints: ['/dashboard/documents'],
        serverEnforcement: ['/api/proxy/document-upload concurrency checks'],
    },
    {
        key: 'document_upload',
        title: 'Document Uploads',
        description: 'Upload and process learning documents.',
        allowedTiers: ['FREE', 'PRO', 'PROMO_PRO'],
        uiEntryPoints: ['/dashboard/documents'],
        serverEnforcement: ['/api/proxy/document-upload'],
        quotaKey: 'max_documents_uploaded_total',
    },
    {
        key: 'prompt_starters',
        title: 'Prompt Starters',
        description: 'Suggested prompts generated by AI.',
        allowedTiers: ['FREE', 'PRO', 'PROMO_PRO'],
        uiEntryPoints: ['/dashboard/chat'],
        serverEnforcement: ['/api/proxy/generate-prompt-starters'],
        quotaKey: 'prompt_starters_per_day',
    },
];
exports.TIER_QUOTA_POLICIES = [
    {
        key: 'messages_per_day',
        description: 'Total AU chat/global chat messages per day.',
        period: 'day',
        freeLimit: 35,
        proLimit: 400,
    },
    {
        key: 'chat_requests_per_minute',
        description: 'Burst control for chat request volume.',
        period: 'minute',
        freeLimit: 8,
        proLimit: 30,
    },
    {
        key: 'knowledge_generations_per_day',
        description: 'Knowledge generation runs per day.',
        period: 'day',
        freeLimit: 4,
        proLimit: 60,
    },
    {
        key: 'prompt_starters_per_day',
        description: 'Prompt starter generations per day.',
        period: 'day',
        freeLimit: 10,
        proLimit: 120,
    },
    {
        key: 'practice_exams_per_day',
        description: 'Practice exam generations per day.',
        period: 'day',
        freeLimit: 0,
        proLimit: 25,
    },
    {
        key: 'predictions_per_day',
        description: 'Exam prediction runs per day.',
        period: 'day',
        freeLimit: 0,
        proLimit: 25,
    },
    {
        key: 'max_documents_uploaded_total',
        description: 'Lifetime total uploaded documents.',
        period: 'lifetime',
        freeLimit: exports.FIXED_MAX_DOCUMENTS_UPLOADED_TOTAL.free,
        proLimit: exports.FIXED_MAX_DOCUMENTS_UPLOADED_TOTAL.pro,
    },
];
exports.TIER_TUNING_POLICY = {
    memoryTurnWindow: {
        free: 8,
        pro: 24,
    },
    retrievalTopK: {
        free: 6,
        pro: 16,
    },
    concurrentJobs: {
        free: 2,
        pro: 8,
    },
    modelAccess: {
        free: 'free_models_only',
        pro: 'paid_models',
    },
};
const FEATURE_BY_KEY = new Map(exports.TIER_FEATURE_POLICIES.map((row) => [row.key, row]));
const QUOTA_BY_KEY = new Map(exports.TIER_QUOTA_POLICIES.map((row) => [row.key, row]));
function toTierRuntime(tier) {
    if (tier === 'PRO')
        return 'pro';
    if (tier === 'PROMO_PRO')
        return 'promo_pro';
    return 'free';
}
function isProLikeTier(tier) {
    return tier === 'PRO' || tier === 'PROMO_PRO';
}
function tierDisplayLabel(tier) {
    if (tier === 'PROMO_PRO')
        return 'Promo Pro';
    if (tier === 'PRO')
        return 'Pro';
    return 'Free';
}
function getFeaturePolicy(key) {
    return FEATURE_BY_KEY.get(key) || null;
}
function getQuotaPolicy(key) {
    return QUOTA_BY_KEY.get(key) || null;
}
function isFeatureAllowedForTier(featureKey, tier) {
    const policy = getFeaturePolicy(featureKey);
    if (!policy)
        return false;
    return policy.allowedTiers.includes(tier);
}
function limitUpgradeHref(limitKey) {
    const source = encodeURIComponent(`limit_${limitKey}`);
    return `/pricing?source=${source}`;
}
function featureUpgradeHref(featureKey) {
    const source = encodeURIComponent(`feature_${featureKey}`);
    return `/pricing?source=${source}`;
}
function getUpgradeBenefits(input) {
    const key = String(input.limitKey || input.featureKey || '').trim().toLowerCase();
    const map = {
        max_documents_uploaded_total: [
            'Upload up to 10 lifetime documents',
            'Higher ingestion concurrency for faster processing',
            'Global chat and cross-document reasoning',
            'Practice exams + prediction engine access',
        ],
        messages_per_day: [
            'Higher daily chat allowance',
            'Deeper memory context in conversations',
            'Global chat access across your library',
            'Priority routing and faster responses',
        ],
        knowledge_generations_per_day: [
            'More daily knowledge generation runs',
            'Richer retrieval depth for roadmap quality',
            'Priority compute during peak traffic',
            'Unlock advanced study workflows',
        ],
        prompt_starters_per_day: [
            'More prompt starter generations daily',
            'Higher quality model pool',
            'Faster response priority',
            'Advanced personalization features',
        ],
        global_chat: [
            'Cross-library question answering',
            'Higher memory depth and context window',
            'Premium model routing',
            'Priority response latency',
        ],
        practice_exam_generation: [
            'Unlimited-style exam prep flow',
            'Practice exam generation access',
            'Premium model quality for exam construction',
            'Priority queue execution',
        ],
        exam_predictions: [
            'Prediction engine access',
            'Higher-cost inference path unlocked',
            'Priority generation speed',
            'Cross-document trend analysis',
        ],
    };
    return map[key] || [
        'Premium model quality',
        'Higher usage limits',
        'Advanced memory depth',
        'Priority processing',
    ];
}
function isPromoWindowActive(now = Date.now()) {
    const endsAt = new Date(exports.PROMO_PRO_END_UTC_ISO).getTime();
    return Number.isFinite(endsAt) && now < endsAt;
}
