export const PROMO_PRO_END_LAGOS_ISO = '2026-04-02T00:00:00+01:00';
export const PROMO_PRO_END_UTC_ISO = '2026-04-01T23:00:00.000Z';

export const UPLOAD_SIZE_FEATURE_FLAG = 'upload_100mb';
export const DEFAULT_MAX_UPLOAD_MB = 50;
export const FLAGGED_MAX_UPLOAD_MB = 100;

export const FIXED_MAX_DOCUMENTS_UPLOADED_TOTAL = {
  free: 4,
  pro: 10,
} as const;

export type TierId = 'FREE' | 'PRO' | 'PROMO_PRO';
export type TierRuntime = 'free' | 'pro' | 'promo_pro';
export type QuotaPeriod = 'minute' | 'hour' | 'day' | 'week' | 'month' | 'lifetime';

export type TierFeatureKey =
  | 'au_chat'
  | 'global_chat'
  | 'knowledge_generation'
  | 'practice_exam_generation'
  | 'exam_predictions'
  | 'premium_models'
  | 'advanced_memory'
  | 'priority_worker_queue'
  | 'document_upload'
  | 'prompt_starters';

export type TierQuotaKey =
  | 'messages_per_day'
  | 'chat_requests_per_minute'
  | 'knowledge_generations_per_day'
  | 'prompt_starters_per_day'
  | 'practice_exams_per_day'
  | 'predictions_per_day'
  | 'max_documents_uploaded_total';

export type TierFeaturePolicy = {
  key: TierFeatureKey;
  title: string;
  description: string;
  allowedTiers: TierId[];
  uiEntryPoints: string[];
  serverEnforcement: string[];
  quotaKey?: TierQuotaKey;
};

export type TierQuotaPolicy = {
  key: TierQuotaKey;
  description: string;
  period: QuotaPeriod;
  freeLimit: number;
  proLimit: number;
  promoProLimit?: number;
};

export type TierTuningPolicy = {
  memoryTurnWindow: {
    free: number;
    pro: number;
  };
  retrievalTopK: {
    free: number;
    pro: number;
  };
  concurrentJobs: {
    free: number;
    pro: number;
  };
  modelAccess: {
    free: 'free_models_only';
    pro: 'paid_models';
  };
};

export const TIER_FEATURE_POLICIES: TierFeaturePolicy[] = [
  {
    key: 'au_chat',
    title: 'AU Chat (single document)',
    description: 'Core chat against selected document context.',
    allowedTiers: ['FREE', 'PRO', 'PROMO_PRO'],
    uiEntryPoints: ['/dashboard/chat'],
    serverEnforcement: ['/api/proxy/chat', '/api/proxy/au-chat'],
    quotaKey: 'messages_per_day',
  },
  {
    key: 'global_chat',
    title: 'Global Chat (cross-library)',
    description: 'Cross-document assistant using broader memory and context.',
    allowedTiers: ['PRO', 'PROMO_PRO'],
    uiEntryPoints: ['/dashboard/global-chat'],
    serverEnforcement: ['/api/proxy/global-chat'],
  },
  {
    key: 'knowledge_generation',
    title: 'Knowledge Generation',
    description: 'Summary, key points, concept mapping, roadmap generation.',
    allowedTiers: ['FREE', 'PRO', 'PROMO_PRO'],
    uiEntryPoints: ['/dashboard/knowledge'],
    serverEnforcement: ['/api/proxy/generate-knowledge'],
    quotaKey: 'knowledge_generations_per_day',
  },
  {
    key: 'practice_exam_generation',
    title: 'Practice Exam Generation',
    description: 'Generates exam simulations from textbook and past questions.',
    allowedTiers: ['PRO', 'PROMO_PRO'],
    uiEntryPoints: ['/dashboard/practice'],
    serverEnforcement: ['/api/proxy/exam-generator'],
    quotaKey: 'practice_exams_per_day',
  },
  {
    key: 'exam_predictions',
    title: 'Exam Prediction Engine',
    description: 'Pattern-weighted exam prediction generation.',
    allowedTiers: ['PRO', 'PROMO_PRO'],
    uiEntryPoints: ['/dashboard/predictions'],
    serverEnforcement: ['/api/proxy/prediction-engine'],
    quotaKey: 'predictions_per_day',
  },
  {
    key: 'premium_models',
    title: 'Premium Model Access',
    description: 'Paid model families and highest quality routing.',
    allowedTiers: ['PRO', 'PROMO_PRO'],
    uiEntryPoints: ['/dashboard/chat', '/dashboard/global-chat'],
    serverEnforcement: ['/api/proxy/[functionName] model selection'],
  },
  {
    key: 'advanced_memory',
    title: 'Advanced Memory Depth',
    description: 'Higher turn window and larger retrieval depth.',
    allowedTiers: ['PRO', 'PROMO_PRO'],
    uiEntryPoints: ['/dashboard/chat', '/dashboard/global-chat'],
    serverEnforcement: ['/api/proxy/chat payload clamp'],
  },
  {
    key: 'priority_worker_queue',
    title: 'Priority Worker Throughput',
    description: 'Higher concurrent processing throughput for ingestion jobs.',
    allowedTiers: ['PRO', 'PROMO_PRO'],
    uiEntryPoints: ['/dashboard/documents'],
    serverEnforcement: ['/api/proxy/document-upload concurrency checks'],
  },
  {
    key: 'document_upload',
    title: 'Document Uploads',
    description: 'Upload and process learning documents.',
    allowedTiers: ['FREE', 'PRO', 'PROMO_PRO'],
    uiEntryPoints: ['/dashboard/documents'],
    serverEnforcement: ['/api/proxy/document-upload'],
    quotaKey: 'max_documents_uploaded_total',
  },
  {
    key: 'prompt_starters',
    title: 'Prompt Starters',
    description: 'Suggested prompts generated by AI.',
    allowedTiers: ['FREE', 'PRO', 'PROMO_PRO'],
    uiEntryPoints: ['/dashboard/chat'],
    serverEnforcement: ['/api/proxy/generate-prompt-starters'],
    quotaKey: 'prompt_starters_per_day',
  },
];

export const TIER_QUOTA_POLICIES: TierQuotaPolicy[] = [
  {
    key: 'messages_per_day',
    description: 'Total AU chat/global chat messages per day.',
    period: 'day',
    freeLimit: 35,
    proLimit: 400,
  },
  {
    key: 'chat_requests_per_minute',
    description: 'Burst control for chat request volume.',
    period: 'minute',
    freeLimit: 8,
    proLimit: 30,
  },
  {
    key: 'knowledge_generations_per_day',
    description: 'Knowledge generation runs per day.',
    period: 'day',
    freeLimit: 4,
    proLimit: 60,
  },
  {
    key: 'prompt_starters_per_day',
    description: 'Prompt starter generations per day.',
    period: 'day',
    freeLimit: 10,
    proLimit: 120,
  },
  {
    key: 'practice_exams_per_day',
    description: 'Practice exam generations per day.',
    period: 'day',
    freeLimit: 0,
    proLimit: 25,
  },
  {
    key: 'predictions_per_day',
    description: 'Exam prediction runs per day.',
    period: 'day',
    freeLimit: 0,
    proLimit: 25,
  },
  {
    key: 'max_documents_uploaded_total',
    description: 'Lifetime total uploaded documents.',
    period: 'lifetime',
    freeLimit: FIXED_MAX_DOCUMENTS_UPLOADED_TOTAL.free,
    proLimit: FIXED_MAX_DOCUMENTS_UPLOADED_TOTAL.pro,
  },
];

export const TIER_TUNING_POLICY: TierTuningPolicy = {
  memoryTurnWindow: {
    free: 8,
    pro: 24,
  },
  retrievalTopK: {
    free: 6,
    pro: 16,
  },
  concurrentJobs: {
    free: 2,
    pro: 8,
  },
  modelAccess: {
    free: 'free_models_only',
    pro: 'paid_models',
  },
};

const FEATURE_BY_KEY = new Map(TIER_FEATURE_POLICIES.map((row) => [row.key, row]));
const QUOTA_BY_KEY = new Map(TIER_QUOTA_POLICIES.map((row) => [row.key, row]));

export function toTierRuntime(tier: TierId): TierRuntime {
  if (tier === 'PRO') return 'pro';
  if (tier === 'PROMO_PRO') return 'promo_pro';
  return 'free';
}

export function isProLikeTier(tier: TierId): boolean {
  return tier === 'PRO' || tier === 'PROMO_PRO';
}

export function tierDisplayLabel(tier: TierId): string {
  if (tier === 'PROMO_PRO') return 'Promo Pro';
  if (tier === 'PRO') return 'Pro';
  return 'Free';
}

export function getFeaturePolicy(key: TierFeatureKey): TierFeaturePolicy | null {
  return FEATURE_BY_KEY.get(key) || null;
}

export function getQuotaPolicy(key: TierQuotaKey): TierQuotaPolicy | null {
  return QUOTA_BY_KEY.get(key) || null;
}

export function isFeatureAllowedForTier(featureKey: TierFeatureKey, tier: TierId): boolean {
  const policy = getFeaturePolicy(featureKey);
  if (!policy) return false;
  return policy.allowedTiers.includes(tier);
}

export function limitUpgradeHref(limitKey: string): string {
  const source = encodeURIComponent(`limit_${limitKey}`);
  return `/pricing?source=${source}`;
}

export function featureUpgradeHref(featureKey: TierFeatureKey): string {
  const source = encodeURIComponent(`feature_${featureKey}`);
  return `/pricing?source=${source}`;
}

export function getUpgradeBenefits(input: { limitKey?: string; featureKey?: TierFeatureKey }): string[] {
  const key = String(input.limitKey || input.featureKey || '').trim().toLowerCase();

  const map: Record<string, string[]> = {
    max_documents_uploaded_total: [
      'Upload up to 10 lifetime documents',
      'Higher ingestion concurrency for faster processing',
      'Global chat and cross-document reasoning',
      'Practice exams + prediction engine access',
    ],
    messages_per_day: [
      'Higher daily chat allowance',
      'Deeper memory context in conversations',
      'Global chat access across your library',
      'Priority routing and faster responses',
    ],
    knowledge_generations_per_day: [
      'More daily knowledge generation runs',
      'Richer retrieval depth for roadmap quality',
      'Priority compute during peak traffic',
      'Unlock advanced study workflows',
    ],
    prompt_starters_per_day: [
      'More prompt starter generations daily',
      'Higher quality model pool',
      'Faster response priority',
      'Advanced personalization features',
    ],
    global_chat: [
      'Cross-library question answering',
      'Higher memory depth and context window',
      'Premium model routing',
      'Priority response latency',
    ],
    practice_exam_generation: [
      'Unlimited-style exam prep flow',
      'Practice exam generation access',
      'Premium model quality for exam construction',
      'Priority queue execution',
    ],
    exam_predictions: [
      'Prediction engine access',
      'Higher-cost inference path unlocked',
      'Priority generation speed',
      'Cross-document trend analysis',
    ],
  };

  return map[key] || [
    'Premium model quality',
    'Higher usage limits',
    'Advanced memory depth',
    'Priority processing',
  ];
}

export function isPromoWindowActive(now = Date.now()): boolean {
  const endsAt = new Date(PROMO_PRO_END_UTC_ISO).getTime();
  return Number.isFinite(endsAt) && now < endsAt;
}
